[package]
name = "rustscript"
version = "0.1.0"
authors = ["Linus Färnstrand <faern@faern.net>", "Simon Andersson <simonasker@posteo.net>"]

[dependencies]
app_dirs = "~1.1"
rust-crypto = "~0.2"
error-chain = "~0.7"
regex = "0.1"
semver = "0.4"
clap = "2.19"
